# Generated by Django 5.2.4 on 2025-07-18 06:54

import django.utils.timezone
import multiselectfield.db.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('provider', 'Provider')], default='Reseller', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='alternative_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='business_type',
            field=models.CharField(choices=[('isp', 'Internet Service Provider (ISP)'), ('regional_partner', 'Regional Partner'), ('local_distributor', 'Local Distributor'), ('premium_reseller', 'Premium Reseller')], default='owner'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='company_name',
            field=models.CharField(default='xyz', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='contact_person',
            field=models.CharField(default='s', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='is_distributor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_provider',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='notes',
            field=models.TextField(default='no'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='position_type',
            field=models.CharField(choices=[('owner', 'Owner'), ('manager', 'Manager'), ('sales_manager', 'Sales Manager'), ('technician', 'Technician'), ('accountant', 'Accountant'), ('customer_support', 'Customer Support'), ('marketing_exec', 'Marketing Executive')], default='s'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(default=1233, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='services',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('sales', 'Sales Support'), ('customer', 'Customer Service'), ('technical', 'Technical Support'), ('billing', 'Billing Management'), ('installation', 'Installation Services'), ('marketing', 'Marketing Support'), ('maintenance', 'Maintenance Services'), ('training', 'Training Programs')], default='sales', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='tax_id',
            field=models.CharField(default=111, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
